spring:
  config:
    import: env.properties
  application:
    name: app

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
#      expiration: 86400000 # 1 day
      expiration: 10000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api/v1/v3/api-docs/swagger-config
    url: /api/v1/v3/api-docs
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.written.app.controller

server:
  port: 8080
  servlet:
    context-path: /api/v1

